# 1. Sum

## Step 1 – Understand the Concept

Sum is the process of adding all the elements in a NumPy array to calculate their total value.

NumPy provides the `np.sum()` function to calculate the sum of array elements.

For example:

`np.sum([10, 20, 30, 40])`

gives:

`100`

The `np.sum()` function can be used with one-dimensional and multi-dimensional arrays.

For a multi-dimensional array, the `axis` parameter can be used to calculate the sum along a specific axis.

Sum is useful when we need to calculate the total value of numerical data.

## Step 2 – Demonstrate the Concept

### 1. Real-World Analogy

Imagine collecting money from four people.

If they give ₹100, ₹200, ₹300, and ₹400, adding all the amounts gives the total money collected.

Similarly, `np.sum()` adds all elements of an array and gives the total.

### 2. Simple Example

Consider the array:

`[10, 20, 30, 40]`

The total is:

`10 + 20 + 30 + 40 = 100`

Therefore:

`np.sum([10, 20, 30, 40])`

gives:

`100`

### 3. Business Example

A shop has the following sales for four days:

`[1000, 1500, 1200, 1800]`

Using `np.sum()`, we can calculate the total sales:

`1000 + 1500 + 1200 + 1800 = 5500`

This helps businesses calculate total sales for a period.

### 4. AI/ML Use Case

In AI/ML and Data Analytics, `np.sum()` can be used to calculate totals from numerical data.

For example, it can be used to calculate total purchases, total revenue, total quantities, or the total values of numerical features during data processing.

In [1]:
# Import NumPy
import numpy as np

# Create a NumPy array
sales = np.array([1000, 1500, 1200, 1800])

# Calculate the total sales
total_sales = np.sum(sales)

# Display the total sales
print(total_sales)

5500


## Step 3 – Implement the Concept

### Code Explanation

- `import numpy as np` imports the NumPy library and gives it the short name `np`.
- `np.array([1000, 1500, 1200, 1800])` creates a NumPy array containing four sales values.
- `np.sum(sales)` adds all the values in the `sales` array.
- The calculated total is stored in `total_sales`.
- `print()` displays the total sales.

### What the Code Does

The code stores four days of sales in a NumPy array.

The `np.sum()` function adds all the values:

`1000 + 1500 + 1200 + 1800 = 5500`

Therefore, the total sales are `5500`.

### Why `np.sum()` Is Used

`np.sum()` is used to quickly calculate the total of numerical values in a NumPy array.

It can calculate the total of many values without writing a separate loop to add each element.

It can also work with multi-dimensional arrays using the `axis` parameter when we need totals across rows or columns.

### Expected Output

```text
5500
The output represents the total sales from the four values in the array.

### Where It Is Used in AI/ML or Data Analytics

np.sum() is commonly used in AI/ML and Data Analytics to calculate totals from numerical datasets.

For example, it can be used to calculate total sales, total purchases, total quantities, or other aggregated numerical values during data analysis and preprocessing.

# 2. Mean

## Step 1 – Understand the Concept

Mean is the average value of a set of numerical data.

It is calculated by adding all the values and dividing the total by the number of values.

The formula is:

**Mean = Sum of all values / Number of values**

NumPy provides the `np.mean()` function to calculate the mean of an array.

For example:

`[10, 20, 30, 40]`

The sum is `100` and there are `4` values.

Therefore:

`Mean = 100 / 4 = 25`

The `np.mean()` function can also be used with the `axis` parameter for calculating the mean across rows or columns in multi-dimensional arrays.

Mean is useful for understanding the average value of numerical data.

## Step 2 – Demonstrate the Concept

### 1. Real-World Analogy

Imagine four students received different marks in a test.

If we want to know the average mark of the group, we add all their marks and divide by the number of students.

This average value represents the mean.

### 2. Simple Example

Consider the values:

`[10, 20, 30, 40]`

The sum is:

`10 + 20 + 30 + 40 = 100`

There are `4` values.

So:

`Mean = 100 / 4 = 25`

Therefore, the mean is `25`.

### 3. Business Example

A shop has the following sales for four days:

`[1000, 1500, 1200, 1800]`

The total sales are `5500`.

There are `4` days.

So:

`Mean = 5500 / 4 = 1375`

The average daily sales are `1375`.

### 4. AI/ML Use Case

In AI/ML, mean is used to understand the average value of numerical features.

For example, the mean age of customers can help us understand the typical age in a dataset.

Mean is also commonly used during data preprocessing and feature scaling techniques such as mean-based standardization.

In [2]:
# Import NumPy
import numpy as np

# Create a NumPy array
marks = np.array([70, 80, 90, 60])

# Calculate the mean
average_marks = np.mean(marks)

# Display the mean
print(average_marks)

75.0


## Step 3 – Implement the Concept

### Code Explanation

- `import numpy as np` imports the NumPy library and gives it the short name `np`.
- `np.array([70, 80, 90, 60])` creates a NumPy array containing four student marks.
- `np.mean(marks)` calculates the average of all the values in the `marks` array.
- The result is stored in `average_marks`.
- `print()` displays the calculated mean.

### What the Code Does

The code stores four marks:

`[70, 80, 90, 60]`

First, the values are added:

`70 + 80 + 90 + 60 = 300`

There are `4` values.

Therefore:

`Mean = 300 / 4 = 75`

So the average mark is `75`.

### Why `np.mean()` Is Used

`np.mean()` is used to calculate the average value of numerical data in a NumPy array.

It performs the calculation directly without requiring us to manually calculate the sum and divide by the number of values.

For multi-dimensional arrays, the `axis` parameter can also be used to calculate means across rows or columns.

### Expected Output

```text
75.0

The output is 75.0 because NumPy returns the mean as a floating-point value.

### Where It Is Used in AI/ML or Data Analytics

Mean is widely used in AI/ML and Data Analytics to understand the average value of numerical data.

It can be used to analyze average age, average sales, average income, or other numerical features.

Mean is also important in data preprocessing and standardization, where the average value of a feature is used to transform the data.

# 3. Median

## Step 1 – Understand the Concept

Median is the middle value of a set of numerical data after the values are arranged in ascending or descending order.

If the dataset contains an odd number of values, the middle value is the median.

If the dataset contains an even number of values, the median is calculated by taking the average of the two middle values.

For example:

`[10, 20, 30, 40, 50]`

The middle value is `30`, so the median is `30`.

For an even number of values:

`[10, 20, 30, 40]`

The two middle values are `20` and `30`.

`Median = (20 + 30) / 2 = 25`

NumPy provides the `np.median()` function to calculate the median of an array.

Median is useful because it is less affected by extreme values or outliers compared with the mean.

## Step 2 – Demonstrate the Concept

### 1. Real-World Analogy

Imagine five people standing in a line from shortest to tallest.

The person standing in the exact middle represents the median position.

Similarly, when numerical values are arranged in order, the middle value is the median.

### 2. Simple Example

Consider:

`[10, 20, 30, 40, 50]`

There are five values, so there is one middle value.

The middle value is `30`.

Therefore, the median is `30`.

For an even number of values:

`[10, 20, 30, 40]`

The two middle values are `20` and `30`.

Their average is:

`(20 + 30) / 2 = 25`

So the median is `25`.

### 3. Business Example

Consider the monthly salaries of employees:

`[20000, 22000, 25000, 28000, 150000]`

The value `150000` is much higher than the other salaries.

It can strongly affect the mean.

The median, however, is `25000`, which gives a better idea of the middle salary in this example.

### 4. AI/ML Use Case

In AI/ML and Data Analytics, median is useful for understanding the center of numerical data, especially when the dataset contains outliers.

For example, median can be used to understand customer income, house prices, transaction amounts, or other numerical features.

Median can also be useful for filling missing numerical values when extreme values are present.

In [3]:
# Import NumPy
import numpy as np

# Create a NumPy array
salaries = np.array([20000, 22000, 25000, 28000, 150000])

# Calculate the median
median_salary = np.median(salaries)

# Display the median
print(median_salary)

25000.0


## Step 3 – Implement the Concept

### Code Explanation

- `import numpy as np` imports the NumPy library and gives it the short name `np`.
- `np.array([20000, 22000, 25000, 28000, 150000])` creates a NumPy array containing employee salary values.
- `np.median(salaries)` calculates the middle value of the salary data.
- The result is stored in `median_salary`.
- `print()` displays the calculated median.

### What the Code Does

The code stores five salary values:

`[20000, 22000, 25000, 28000, 150000]`

The values are already arranged in ascending order.

There are five values, so the middle value is the third value:

`25000`

Therefore, the median salary is `25000`.

The high salary of `150000` does not change the middle position.

### Why `np.median()` Is Used

`np.median()` is used to find the middle value of numerical data.

It is especially useful when the dataset contains extreme values or outliers because the median is less affected by them than the mean.

### Expected Output

```text
25000.0

The output is 25000.0 because NumPy returns the median as a floating-point value.

### Where It Is Used in AI/ML or Data Analytics

Median is commonly used in AI/ML and Data Analytics to understand the center of numerical data.

It is useful for analyzing salaries, income, house prices, transaction amounts, and other data that may contain extreme values.

Median can also be used during data preprocessing, such as replacing missing numerical values when the data contains outliers.

# 4. Variance

## Step 1 – Understand the Concept

Variance measures how far the values in a dataset are spread out from their mean.

A small variance means that the values are close to the mean.

A large variance means that the values are more spread out from the mean.

The population variance formula is:

**Variance = Σ(x − μ)² / N**

Where:

- `x` represents each value.
- `μ` represents the mean.
- `N` represents the total number of values.

NumPy provides the `np.var()` function to calculate variance.

For example, if all values are the same, the variance is `0` because there is no variation between the values.

Variance is useful for understanding the spread or variability of numerical data.

## Step 2 – Demonstrate the Concept

### 1. Real-World Analogy

Imagine two groups of students.

In Group A, all students have marks close to each other.

In Group B, some students have very low marks while others have very high marks.

Group A has lower variance because the marks are close together.

Group B has higher variance because the marks are more spread out.

### 2. Simple Example

Consider:

`[10, 10, 10, 10]`

The mean is `10`.

Every value is exactly equal to the mean, so there is no spread.

Therefore, the variance is `0`.

Now consider:

`[5, 10, 15, 20]`

The values are more spread out from their mean, so the variance is higher.

### 3. Business Example

A company can use variance to understand the variation in daily sales.

If daily sales are:

`[1000, 1050, 1100, 1080]`

the values are close together, so the variance is relatively small.

If daily sales are:

`[500, 1000, 2000, 3500]`

the values are much more spread out, so the variance is higher.

### 4. AI/ML Use Case

In AI/ML, variance is used to understand how much a numerical feature varies across a dataset.

For example, variance can help analyze the variation in customer age, income, transaction amount, or other numerical features.

Variance is also an important statistical concept when studying feature selection, data preprocessing, and model behavior.

In [4]:
# Import NumPy
import numpy as np

# Create a NumPy array
marks = np.array([60, 70, 80, 90, 100])

# Calculate the variance
variance = np.var(marks)

# Display the variance
print(variance)

200.0


## Step 3 – Implement the Concept

### Code Explanation

- `import numpy as np` imports the NumPy library and gives it the short name `np`.
- `np.array([60, 70, 80, 90, 100])` creates a NumPy array containing five marks.
- `np.var(marks)` calculates the population variance of the marks.
- The result is stored in `variance`.
- `print()` displays the calculated variance.

### What the Code Does

The code stores the marks:

`[60, 70, 80, 90, 100]`

First, the mean is calculated:

`Mean = 80`

Then, each value's difference from the mean is considered and squared.

The squared differences are:

`400, 100, 0, 100, 400`

Their sum is:

`1000`

There are `5` values.

Therefore:

`Variance = 1000 / 5 = 200`

### Why `np.var()` Is Used

`np.var()` is used to calculate the variance of numerical data.

It helps us understand how much the values vary or spread around their mean.

By default, `np.var()` calculates the population variance using division by `N`.

### Expected Output

```text
200.0

The output 200.0 represents the variance of the marks.

A higher variance would indicate that the values are more spread out from their mean.

### Where It Is Used in AI/ML or Data Analytics

Variance is widely used in AI/ML and Data Analytics to measure the variability of numerical features.

It can help identify features with very little or high variation and is used in statistical analysis and some feature-selection and preprocessing techniques.

# 5. Standard Deviation

## Step 1 – Understand the Concept

Standard deviation measures how much the values in a dataset are spread out from their mean.

A small standard deviation means that the values are close to the mean.

A large standard deviation means that the values are more spread out from the mean.

Standard deviation is related to variance:

**Standard Deviation = √Variance**

The population standard deviation formula is:

**σ = √(Σ(x − μ)² / N)**

Where:

- `x` represents each value.
- `μ` represents the mean.
- `N` represents the total number of values.

NumPy provides the `np.std()` function to calculate standard deviation.

Standard deviation is easier to interpret than variance because it is expressed in the same unit as the original data.

## Step 2 – Demonstrate the Concept

### 1. Real-World Analogy

Imagine two groups of students taking the same test.

If the marks of one group are very close to their average, the standard deviation will be small.

If the marks of another group are very different from their average, the standard deviation will be large.

So, standard deviation tells us how spread out the values are.

### 2. Simple Example

Consider:

`[10, 10, 10, 10]`

The mean is `10`.

All values are equal to the mean, so there is no spread.

Therefore:

`Standard Deviation = 0`

Now consider:

`[5, 10, 15, 20]`

The values are more spread out from the mean, so the standard deviation is higher.

### 3. Business Example

A company can use standard deviation to understand the variation in daily sales.

If daily sales are:

`[1000, 1050, 1100, 1080]`

the values are close together, so the standard deviation is small.

If daily sales are:

`[500, 1000, 2000, 3500]`

the values are more spread out, so the standard deviation is larger.

### 4. AI/ML Use Case

In AI/ML, standard deviation is used to understand the spread of numerical features.

It is also important in data preprocessing and standardization.

For example, a feature can be transformed using its mean and standard deviation so that values are represented relative to the feature's average and spread.

In [5]:
# Import NumPy
import numpy as np

# Create a NumPy array
marks = np.array([60, 70, 80, 90, 100])

# Calculate the standard deviation
standard_deviation = np.std(marks)

# Display the standard deviation
print(standard_deviation)

14.142135623730951


## Step 3 – Implement the Concept

### Code Explanation

- `import numpy as np` imports the NumPy library and gives it the short name `np`.
- `np.array([60, 70, 80, 90, 100])` creates a NumPy array containing five marks.
- `np.std(marks)` calculates the population standard deviation of the marks.
- The result is stored in `standard_deviation`.
- `print()` displays the calculated standard deviation.

### What the Code Does

The code stores the marks:

`[60, 70, 80, 90, 100]`

The mean of the values is:

`80`

The variance of these values is:

`200`

Standard deviation is the square root of variance:

`√200 ≈ 14.14`

Therefore, the standard deviation is approximately `14.14`.

### Why `np.std()` Is Used

`np.std()` is used to calculate how much the values in an array vary from their mean.

It is useful because the result is expressed in the same unit as the original data.

By default, `np.std()` calculates the population standard deviation.

### Expected Output

```text
14.142135623730951

The output represents the standard deviation of the marks.

A smaller value means the data points are closer to the mean, while a larger value means they are more spread out.

### Where It Is Used in AI/ML or Data Analytics

Standard deviation is widely used in AI/ML and Data Analytics to understand the spread and variability of numerical features.

It is also used in data preprocessing and feature standardization, where the mean and standard deviation of a feature are used to transform its values.

# 6. Minimum

## Step 1 – Understand the Concept

Minimum is the smallest value present in a NumPy array.

NumPy provides the `np.min()` function to find the smallest value in an array.

For example:

`[10, 25, 5, 40, 15]`

The smallest value is `5`.

Therefore:

`np.min([10, 25, 5, 40, 15])`

gives:

`5`

The `np.min()` function can also be used with the `axis` parameter to find minimum values across rows or columns in a multi-dimensional array.

Minimum is useful when we need to identify the lowest value in numerical data.

## Step 2 – Demonstrate the Concept

### 1. Real-World Analogy

Imagine five people have different amounts of money.

If we want to know who has the least amount of money, we look for the smallest value.

Similarly, `np.min()` finds the smallest value in an array.

### 2. Simple Example

Consider:

`[10, 25, 5, 40, 15]`

The smallest value is:

`5`

Therefore:

`np.min(numbers)`

returns:

`5`

### 3. Business Example

A store has product prices:

`[500, 750, 450, 900]`

The minimum price is:

`450`

This can help a business identify the lowest-priced product or the lowest value in a group of products.

### 4. AI/ML Use Case

In AI/ML and Data Analytics, minimum values can be used to understand the lower range of numerical features.

For example, we can find the minimum customer age, minimum income, minimum transaction amount, or minimum sales value in a dataset.

In [6]:
# Import NumPy
import numpy as np

# Create a NumPy array
prices = np.array([500, 750, 450, 900, 600])

# Find the minimum price
minimum_price = np.min(prices)

# Display the minimum price
print(minimum_price)

450


## Step 3 – Implement the Concept

### Code Explanation

- `import numpy as np` imports the NumPy library and gives it the short name `np`.
- `np.array([500, 750, 450, 900, 600])` creates a NumPy array containing product prices.
- `np.min(prices)` finds the smallest value in the `prices` array.
- The result is stored in `minimum_price`.
- `print()` displays the minimum price.

### What the Code Does

The code stores five product prices:

`[500, 750, 450, 900, 600]`

The smallest value in the array is:

`450`

Therefore, `np.min()` returns `450`.

### Why `np.min()` Is Used

`np.min()` is used to quickly find the smallest value in a NumPy array.

It is useful when we need to identify the lowest value in numerical data without manually comparing every element.

For multi-dimensional arrays, the `axis` parameter can be used to find minimum values across specific rows or columns.

### Expected Output

```text
450

The output represents the lowest price in the array.

### Where It Is Used in AI/ML or Data Analytics

np.min() is used in AI/ML and Data Analytics to understand the lower range of numerical data.

For example, it can be used to find the minimum age, salary, sales, transaction amount, or other numerical feature values during data analysis and preprocessing.

# 7. Maximum

## Step 1 – Understand the Concept

Maximum is the largest value present in a dataset or NumPy array.

NumPy provides the `np.max()` function to find the maximum value.

### Syntax

`np.max(array)`

The `axis` parameter can be used to find maximum values across rows or columns in a multi-dimensional array.

### Example

For the array `[10, 25, 5, 40, 15]`, the maximum value is `40`.

### Difference Between max() and argmax()

- `np.max()` returns the largest value.
- `np.argmax()` returns the index position of the largest value.

## Step 2 – Demonstrate the Concept

### Real-World Analogy

Imagine checking the temperature for five days. The highest temperature is the maximum temperature.

### Simple Example

For the values `[10, 25, 5, 40, 15]`, the maximum value is `40`.

### Business Example

A company can use the maximum function to find the highest sales amount recorded during a period.

### AI/ML Use Case

In AI/ML and Data Analytics, the maximum function can be used to identify the highest value of a numerical feature, such as maximum salary, maximum age, maximum transaction amount, or maximum sales.

In [7]:
# Import NumPy
import numpy as np

# Create a NumPy array
sales = np.array([1000, 1500, 1200, 1800, 1600])

# Find the maximum sales value
maximum_sales = np.max(sales)

# Display the maximum sales value
print(maximum_sales)

1800


## Step 3 – Explanation

### Code Explanation

- `import numpy as np` imports the NumPy library.
- `sales = np.array(...)` creates a NumPy array containing sales values.
- `np.max(sales)` finds the largest value in the array.
- `maximum_sales` stores the maximum sales value.
- `print(maximum_sales)` displays the result.

### What the Code Does

The code finds the highest sales amount from the given sales data.

### Why `np.max()` Is Used

`np.max()` is used to quickly identify the largest value in a NumPy array.

### Expected Output

`1800`

This means the highest sales value in the array is 1800.

### Where It Is Used in AI/ML or Data Analytics

Maximum is used to understand the upper range of numerical data. It can help identify the highest salary, transaction amount, sales value, temperature, or other numerical feature during data analysis and preprocessing.



# 8. Argmin

## Step 1 – Understand the Concept

Argmin returns the index position of the smallest value in a NumPy array.

NumPy provides the `np.argmin()` function to find the index of the minimum value.

### Syntax

`np.argmin(array)`

### Example

For the array `[10, 25, 5, 40, 15]`:

- Minimum value = `5`
- Index of minimum value = `2`

Therefore, `np.argmin()` returns `2`.

### Difference Between min() and argmin()

- `np.min()` returns the smallest value.
- `np.argmin()` returns the index position of the smallest value.

## Step 2 – Demonstrate the Concept

### Real-World Analogy

Imagine checking the temperature for five days. Argmin helps identify the position of the day with the lowest temperature.

### Simple Example

For `[10, 25, 5, 40, 15]`, the smallest value is `5`, and its index is `2`.

### Business Example

A company can use argmin to identify the position of the product with the lowest price.

### AI/ML Use Case

In AI/ML and Data Analytics, argmin can be used to identify the position of the smallest value in numerical data, such as finding the sample with the lowest prediction error or lowest feature value.

In [8]:
# Import NumPy
import numpy as np

# Create a NumPy array
prices = np.array([500, 750, 450, 900, 600])

# Find the index of the minimum price
minimum_index = np.argmin(prices)

# Display the index
print(minimum_index)

2


## Step 3 – Explanation

### Code Explanation

- `import numpy as np` imports the NumPy library.
- `prices = np.array(...)` creates a NumPy array containing product prices.
- `np.argmin(prices)` finds the index position of the smallest price.
- `minimum_index` stores the index returned by `np.argmin()`.
- `print(minimum_index)` displays the index.

### What the Code Does

The code finds the position of the lowest price in the NumPy array.

### Why `np.argmin()` Is Used

`np.argmin()` is used when we need the position or index of the smallest value instead of the smallest value itself.

### Expected Output

`2`

The value at index `2` is `450`, which is the lowest price.

### Where It Is Used in AI/ML or Data Analytics

Argmin can be used to identify the position of the minimum value in numerical data, such as finding the sample with the lowest error, lowest cost, or lowest feature value.

# 9. Argmax

## Step 1 – Understand the Concept

Argmax returns the index position of the largest value in a NumPy array.

NumPy provides the `np.argmax()` function to find the index of the maximum value.

### Syntax

`np.argmax(array)`

### Example

For the array `[10, 25, 5, 40, 15]`:

- Maximum value = `40`
- Index of maximum value = `3`

Therefore, `np.argmax()` returns `3`.

### Difference Between max() and argmax()

- `np.max()` returns the largest value.
- `np.argmax()` returns the index position of the largest value.

## Step 2 – Demonstrate the Concept

### Real-World Analogy

Imagine checking the temperature for five days. Argmax helps identify the position of the day with the highest temperature.

### Simple Example

For `[10, 25, 5, 40, 15]`, the largest value is `40`, and its index is `3`.

### Business Example

A company can use argmax to identify the position of the product with the highest sales.

### AI/ML Use Case

In AI/ML, argmax is commonly used to identify the class with the highest prediction probability. For example, if a model gives probabilities `[0.10, 0.70, 0.20]`, argmax returns `1`, which represents the class with the highest probability.

In [9]:
# Import NumPy
import numpy as np

# Create a NumPy array
sales = np.array([1000, 1500, 1200, 1800, 1600])

# Find the index of the maximum sales value
maximum_index = np.argmax(sales)

# Display the index
print(maximum_index)

3


## Step 3 – Explanation

### Code Explanation

- `import numpy as np` imports the NumPy library.
- `sales = np.array(...)` creates a NumPy array containing sales values.
- `np.argmax(sales)` finds the index position of the largest sales value.
- `maximum_index` stores the index returned by `np.argmax()`.
- `print(maximum_index)` displays the index.

### What the Code Does

The code finds the position of the highest sales value in the NumPy array.

### Why `np.argmax()` Is Used

`np.argmax()` is used when we need the position or index of the largest value instead of the largest value itself.

### Expected Output

`3`

The value at index `3` is `1800`, which is the highest sales value.

### Where It Is Used in AI/ML or Data Analytics

Argmax is commonly used in AI/ML to select the class with the highest prediction probability. It is also useful for identifying the position of the highest value in numerical datasets.

# 10. Percentile

## Step 1 – Understand the Concept

A percentile tells us the value below which a given percentage of observations in a dataset falls.

NumPy provides the `np.percentile()` function to calculate percentiles.

### Syntax

`np.percentile(array, percentile)`

### Example

For a dataset, the 50th percentile represents the middle part of the data and is related to the median.

The 25th percentile is called Q1, and the 75th percentile is called Q3.

### Formula Idea

The Pth percentile represents the value below which approximately P% of the observations fall.

## Step 2 – Demonstrate the Concept

### Real-World Analogy

Imagine the marks of students arranged from lowest to highest. The 90th percentile tells us the score below which approximately 90% of the students' marks fall.

### Simple Example

For the data `[10, 20, 30, 40, 50]`, the 50th percentile is `30`.

### Business Example

A company can calculate the 75th percentile of customer spending to understand the spending level of higher-spending customers.

### AI/ML Use Case

Percentiles are useful in AI/ML and Data Analytics for understanding feature distributions, detecting extreme values, and identifying potential outliers.

In [10]:
# Import NumPy
import numpy as np

# Create a NumPy array
marks = np.array([10, 20, 30, 40, 50])

# Calculate the 50th percentile
percentile_50 = np.percentile(marks, 50)

# Display the result
print(percentile_50)

30.0


## Step 3 – Explanation

### Code Explanation

- `import numpy as np` imports the NumPy library.
- `marks = np.array(...)` creates a NumPy array containing marks.
- `np.percentile(marks, 50)` calculates the 50th percentile.
- `percentile_50` stores the calculated result.
- `print(percentile_50)` displays the result.

### What the Code Does

The code calculates the 50th percentile of the given marks.

### Why `np.percentile()` Is Used

`np.percentile()` is used to understand the position of data values within a dataset and to divide data into percentage-based levels.

### Expected Output

`30.0`

This means the 50th percentile of the given dataset is 30.

### Where It Is Used in AI/ML or Data Analytics

Percentiles are used to understand data distributions, identify thresholds, analyze customer or business data, and detect potential outliers during data analysis and preprocessing.

# 11. Dot Product

## Step 1 – Understand the Concept

The dot product is the sum of the products of corresponding elements of two arrays.

### Formula

`A · B = A₁B₁ + A₂B₂ + ... + AₙBₙ`

NumPy provides the `np.dot()` function to calculate the dot product.

### Syntax

`np.dot(array1, array2)`

### Example

For:

`A = [1, 2, 3]`

`B = [4, 5, 6]`

The dot product is:

`(1 × 4) + (2 × 5) + (3 × 6) = 32`

## Step 2 – Demonstrate the Concept

### Real-World Analogy

Imagine buying three products. For each product, multiply its quantity by its price and then add all the results to get the total amount.

### Simple Example

For `[1, 2, 3]` and `[4, 5, 6]`:

`(1 × 4) + (2 × 5) + (3 × 6) = 32`

### Business Example

A business can use the dot product to calculate total revenue from multiple products using their quantities and prices.

### AI/ML Use Case

In AI/ML, the dot product is used to combine feature values with model weights. It is a fundamental operation in linear models and neural networks.

In [11]:
# Import NumPy
import numpy as np

# Create two NumPy arrays
quantities = np.array([2, 3, 4])
prices = np.array([100, 200, 150])

# Calculate the dot product
total_revenue = np.dot(quantities, prices)

# Display the total revenue
print(total_revenue)


1400


## Step 3 – Explanation

### Code Explanation

- `import numpy as np` imports the NumPy library.
- `quantities` stores the quantity of each product.
- `prices` stores the price of each corresponding product.
- `np.dot(quantities, prices)` multiplies the corresponding values and adds the results.
- `total_revenue` stores the calculated total.
- `print(total_revenue)` displays the result.

### What the Code Does

The code calculates the total revenue using the quantity and price of multiple products.

The calculation is:

`(2 × 100) + (3 × 200) + (4 × 150)`

`= 200 + 600 + 600`

`= 1400`

### Why `np.dot()` Is Used

`np.dot()` is used to efficiently calculate the dot product of two arrays.

### Expected Output

`1400`

This means the total revenue calculated from the given quantities and prices is 1400.

### Where It Is Used in AI/ML or Data Analytics

The dot product is widely used in AI/ML for calculating weighted sums, combining features with model weights, linear regression calculations, and neural network operations.

# 12. Matrix Multiplication

## Step 1 – Understand the Concept

Matrix multiplication is an operation where rows of the first matrix are multiplied with columns of the second matrix and the products are added.

NumPy provides `np.matmul()` and the `@` operator for matrix multiplication.

### Syntax

`np.matmul(matrix1, matrix2)`

or

`matrix1 @ matrix2`

### Important Rule

For matrix multiplication, the number of columns in the first matrix must be equal to the number of rows in the second matrix.

### Example

For two 2 × 2 matrices:

`A = [[1, 2], [3, 4]]`

`B = [[5, 6], [7, 8]]`

The result is:

`[[19, 22], [43, 50]]`

## Step 2 – Demonstrate the Concept

### Real-World Analogy

Imagine combining information from different groups. Each row contains one set of values, and each column contains another set of values. Matrix multiplication combines them using multiplication and addition.

### Simple Example

For:

`A = [[1, 2], [3, 4]]`

and

`B = [[5, 6], [7, 8]]`

the result is:

`[[19, 22], [43, 50]]`

### Business Example

A business can use matrix multiplication to combine product quantities, prices, or other numerical business data for calculations across multiple products.

### AI/ML Use Case

Matrix multiplication is a fundamental operation in AI/ML. It is used in neural networks, linear models, transformations, and calculations involving features and weights.

In [12]:
# Import NumPy
import numpy as np

# Create the first matrix
A = np.array([[1, 2],
              [3, 4]])

# Create the second matrix
B = np.array([[5, 6],
              [7, 8]])

# Perform matrix multiplication
result = np.matmul(A, B)

# Display the result
print(result)

[[19 22]
 [43 50]]


## Step 3 – Explanation

### Code Explanation

- `import numpy as np` imports the NumPy library.
- `A` creates the first 2 × 2 matrix.
- `B` creates the second 2 × 2 matrix.
- `np.matmul(A, B)` performs matrix multiplication.
- `result` stores the resulting matrix.
- `print(result)` displays the result.

### What the Code Does

The code multiplies two 2 × 2 matrices.

The calculations are:

`(1 × 5) + (2 × 7) = 19`

`(1 × 6) + (2 × 8) = 22`

`(3 × 5) + (4 × 7) = 43`

`(3 × 6) + (4 × 8) = 50`

Therefore, the result is:

`[[19, 22], [43, 50]]`

### Why `np.matmul()` Is Used

`np.matmul()` is used to perform matrix multiplication according to matrix multiplication rules.

### Expected Output

`[[19 22]`

` [43 50]]`

### Where It Is Used in AI/ML or Data Analytics

Matrix multiplication is widely used in AI/ML for neural network computations, linear transformations, feature-weight calculations, and other mathematical operations involving matrices.

# 13. Transpose

## Step 1 – Understand the Concept

Transpose is an operation that changes the rows of a matrix into columns and the columns into rows.

NumPy provides the `.T` attribute and `np.transpose()` function to find the transpose of an array.

### Syntax

`array.T`

or

`np.transpose(array)`

### Example

For:

`A = [[1, 2, 3], [4, 5, 6]]`

The transpose is:

`[[1, 4], [2, 5], [3, 6]]`

A 2 × 3 matrix becomes a 3 × 2 matrix after transposition.

## Step 2 – Demonstrate the Concept

### Real-World Analogy

Imagine a table where students are listed in rows and subjects are listed in columns. Transposing the table changes students from rows to columns and subjects from columns to rows.

### Simple Example

For the matrix:

`[[1, 2, 3], [4, 5, 6]]`

the transpose becomes:

`[[1, 4], [2, 5], [3, 6]]`

### Business Example

A business dataset may store products as rows and features as columns. Transposing can change the orientation when a particular mathematical calculation requires features as rows.

### AI/ML Use Case

Transpose is commonly used in AI/ML matrix calculations, data transformations, and linear algebra operations involving features, weights, and matrices.

In [13]:
# Import NumPy
import numpy as np

# Create a NumPy matrix
data = np.array([[1, 2, 3],
                 [4, 5, 6]])

# Find the transpose of the matrix
transposed_data = data.T

# Display the original matrix
print("Original Matrix:")
print(data)

# Display the transposed matrix
print("Transposed Matrix:")
print(transposed_data)

Original Matrix:
[[1 2 3]
 [4 5 6]]
Transposed Matrix:
[[1 4]
 [2 5]
 [3 6]]


## Step 3 – Explanation

### Code Explanation

- `import numpy as np` imports the NumPy library.
- `data = np.array(...)` creates a 2 × 3 NumPy matrix.
- `data.T` changes the rows into columns and the columns into rows.
- `transposed_data` stores the transposed matrix.
- `print()` displays both the original and transposed matrices.

### What the Code Does

The code changes the orientation of the matrix from 2 rows × 3 columns to 3 rows × 2 columns.

### Why `.T` Is Used

The `.T` attribute is used to quickly find the transpose of a NumPy array.

### Expected Output

Original matrix:

`[[1 2 3]`

` [4 5 6]]`

Transposed matrix:

`[[1 4]`

` [2 5]`

` [3 6]]`

### Where It Is Used in AI/ML or Data Analytics

Transpose is used in AI/ML and Data Analytics for changing data orientation, preparing matrices for mathematical operations, and performing linear algebra calculations involving features and model weights.

# 14. Basic Linear Algebra Operations

## Step 1 – Understand the Concept

Linear algebra is a branch of mathematics that works with vectors, matrices, and mathematical operations between them.

Basic linear algebra operations in NumPy include:

- Matrix addition
- Matrix subtraction
- Scalar multiplication
- Dot product
- Matrix multiplication
- Transpose

### Common NumPy Operations

- `A + B` → Matrix addition
- `A - B` → Matrix subtraction
- `2 * A` → Scalar multiplication
- `np.dot(A, B)` → Dot product
- `np.matmul(A, B)` → Matrix multiplication
- `A.T` → Transpose

These operations are important for working with numerical data and mathematical calculations in AI/ML.

## Step 2 – Demonstrate the Concept

### Real-World Analogy

Imagine two tables containing numerical information. We can add or subtract corresponding values, multiply all values by a number, or change the orientation of the table using transpose.

### Simple Example

For two matrices:

`A = [[1, 2], [3, 4]]`

`B = [[5, 6], [7, 8]]`

Matrix addition gives:

`[[6, 8], [10, 12]]`

### Business Example

A business can use matrix operations to combine numerical information such as product quantities, prices, sales, or customer data.

### AI/ML Use Case

Linear algebra operations are fundamental in AI/ML. They are used for feature calculations, model weights, predictions, transformations, linear regression, and neural network computations.

In [14]:
# Import NumPy
import numpy as np

# Create two matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Matrix addition
addition = A + B

# Matrix subtraction
subtraction = A - B

# Scalar multiplication
scalar_multiplication = 2 * A

# Dot product
dot_product = np.dot(A, B)

# Matrix multiplication
matrix_multiplication = np.matmul(A, B)

# Transpose
transpose = A.T

# Display the results
print("Addition:")
print(addition)

print("Subtraction:")
print(subtraction)

print("Scalar Multiplication:")
print(scalar_multiplication)

print("Dot Product:")
print(dot_product)

print("Matrix Multiplication:")
print(matrix_multiplication)

print("Transpose:")
print(transpose)

Addition:
[[ 6  8]
 [10 12]]
Subtraction:
[[-4 -4]
 [-4 -4]]
Scalar Multiplication:
[[2 4]
 [6 8]]
Dot Product:
[[19 22]
 [43 50]]
Matrix Multiplication:
[[19 22]
 [43 50]]
Transpose:
[[1 3]
 [2 4]]


## Step 3 – Explanation

### Code Explanation

- `import numpy as np` imports the NumPy library.
- `A` and `B` create two NumPy matrices.
- `A + B` performs matrix addition.
- `A - B` performs matrix subtraction.
- `2 * A` multiplies every element of matrix `A` by 2.
- `np.dot(A, B)` calculates the dot product.
- `np.matmul(A, B)` performs matrix multiplication.
- `A.T` finds the transpose of matrix `A`.
- `print()` displays each result.

### What the Code Does

The code demonstrates common linear algebra operations using NumPy matrices.

### Why These Operations Are Used

- `+` is used to add corresponding matrix elements.
- `-` is used to subtract corresponding matrix elements.
- `*` with a scalar is used to scale all matrix values.
- `np.dot()` is used for dot product calculations.
- `np.matmul()` is used for matrix multiplication.
- `.T` is used to transpose a matrix.

### Expected Output

The code produces the results of addition, subtraction, scalar multiplication, dot product, matrix multiplication, and transpose.

### Where It Is Used in AI/ML or Data Analytics

Linear algebra is a foundation of AI/ML. These operations are used in feature transformations, weighted calculations, linear regression, predictions, neural networks, and many other machine learning algorithms.